apiVersion: v1
kind: Service
metadata:
  name: matches-service 
  labels:
   app: matches
spec:
  type: NodePort
  selector:
    app: matches # Select pods with this label
  ports:
  - protocol: TCP          # Protocol
    port: 80  #port exposed within the cluster
    targetPort: 80  # Port on the pods
    nodePort: 30080   # Port accessible externally on each node
 